### ISSUE TITLE
Option for running without emit

### ISSUE THREAD

**Issue by danielwaltz** [policyfly/vue-script-tsc#8]
Hello!

Tried out this package in my project and really like the speed of type checking, but noticed that by default it's generating and writing files to the file system in my source code.

Is there a way to run this where the files are checked in memory, or maybe in a separate cache folder?

Thanks for your work on this!

**Comment by BenShelton** [comment]
Thanks, glad you like it.

Are you using the `compilerOptions.noEmit` option in your tsconfig.json? That should prevent the output you're seeing. See the following from one of the text fixtures (in particular line 8):

https://github.com/policyfly/vue-script-tsc/blob/de94d62bedfe21f61f0de53130433958fb817673/tests/fixtures/tsconfig.clean.json#L2-L9

**Comment by danielwaltz** [comment]
That was the problem! Adding `"noEmit": true` to my `tsconfig.json` solved it. Thank you for the quick response! I'll go ahead and close this but leave it around in case others run into this problem like I did.
